// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsDBLayer;

namespace ProductsDBLayer.Migrations
{
    [DbContext(typeof(ProductsDBContext))]
    [Migration("20211021161305_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductsModel.Category", b =>
                {
                    b.Property<long>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cat_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("value");

                    b.HasKey("CatId")
                        .HasName("PK_38");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ProductsModel.Color", b =>
                {
                    b.Property<long>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("color_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("value");

                    b.HasKey("ColorId");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("ProductsModel.Description", b =>
                {
                    b.Property<long>("DescId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("desc_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("long_description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("title");

                    b.HasKey("DescId")
                        .HasName("PK_27");

                    b.ToTable("Description");
                });

            modelBuilder.Entity("ProductsModel.Image", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("image_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("location");

                    b.Property<string>("MiniDesc")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("mini_desc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("ImageId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("ProductsModel.Mass", b =>
                {
                    b.Property<long>("MassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("mass_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("MassInKg")
                        .HasColumnType("float")
                        .HasColumnName("massInKg");

                    b.HasKey("MassId");

                    b.ToTable("Mass");
                });

            modelBuilder.Entity("ProductsModel.MiscDetail", b =>
                {
                    b.Property<long>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("detail_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("value");

                    b.HasKey("DetailId")
                        .HasName("PK_42");

                    b.ToTable("Misc_Detail");
                });

            modelBuilder.Entity("ProductsModel.Product", b =>
                {
                    b.Property<long>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("prod_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ImageId")
                        .HasColumnType("bigint")
                        .HasColumnName("image_id");

                    b.Property<long>("SizeId")
                        .HasColumnType("bigint")
                        .HasColumnName("size_id");

                    b.Property<long>("CatId")
                        .HasColumnType("bigint")
                        .HasColumnName("cat_id");

                    b.Property<long>("ColorId")
                        .HasColumnType("bigint")
                        .HasColumnName("color_id");

                    b.Property<long>("MassId")
                        .HasColumnType("bigint")
                        .HasColumnName("mass_id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("brand");

                    b.Property<long>("DescId")
                        .HasColumnType("bigint")
                        .HasColumnName("desc_id");

                    b.Property<string>("Designer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("designer");

                    b.Property<long>("DetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("detail_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.HasKey("ProdId", "ImageId", "SizeId", "CatId", "ColorId", "MassId")
                        .HasName("PK_69");

                    b.HasIndex(new[] { "ImageId" }, "fkIdx_50");

                    b.HasIndex(new[] { "DescId" }, "fkIdx_53");

                    b.HasIndex(new[] { "SizeId" }, "fkIdx_56");

                    b.HasIndex(new[] { "CatId" }, "fkIdx_59");

                    b.HasIndex(new[] { "MassId" }, "fkIdx_62");

                    b.HasIndex(new[] { "ColorId" }, "fkIdx_65");

                    b.HasIndex(new[] { "DetailId" }, "fkIdx_68");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ProductsModel.Size", b =>
                {
                    b.Property<long>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("size_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("HeightInMm")
                        .HasColumnType("float")
                        .HasColumnName("HeightInMM");

                    b.Property<double?>("LengthInMm")
                        .HasColumnType("float")
                        .HasColumnName("LengthInMM");

                    b.Property<double?>("WidthInMm")
                        .HasColumnType("float")
                        .HasColumnName("WidthInMM");

                    b.HasKey("SizeId");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("ProductsModel.Product", b =>
                {
                    b.HasOne("ProductsModel.Category", "Cat")
                        .WithMany("Products")
                        .HasForeignKey("CatId")
                        .HasConstraintName("FK_57")
                        .IsRequired();

                    b.HasOne("ProductsModel.Color", "Color")
                        .WithMany("Products")
                        .HasForeignKey("ColorId")
                        .HasConstraintName("FK_63")
                        .IsRequired();

                    b.HasOne("ProductsModel.Description", "Desc")
                        .WithMany("Products")
                        .HasForeignKey("DescId")
                        .HasConstraintName("FK_51")
                        .IsRequired();

                    b.HasOne("ProductsModel.MiscDetail", "Detail")
                        .WithMany("Products")
                        .HasForeignKey("DetailId")
                        .HasConstraintName("FK_66")
                        .IsRequired();

                    b.HasOne("ProductsModel.Image", "Image")
                        .WithMany("Products")
                        .HasForeignKey("ImageId")
                        .HasConstraintName("FK_48")
                        .IsRequired();

                    b.HasOne("ProductsModel.Mass", "Mass")
                        .WithMany("Products")
                        .HasForeignKey("MassId")
                        .HasConstraintName("FK_60")
                        .IsRequired();

                    b.HasOne("ProductsModel.Size", "Size")
                        .WithMany("Products")
                        .HasForeignKey("SizeId")
                        .HasConstraintName("FK_54")
                        .IsRequired();

                    b.Navigation("Cat");

                    b.Navigation("Color");

                    b.Navigation("Desc");

                    b.Navigation("Detail");

                    b.Navigation("Image");

                    b.Navigation("Mass");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("ProductsModel.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductsModel.Color", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductsModel.Description", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductsModel.Image", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductsModel.Mass", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductsModel.MiscDetail", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductsModel.Size", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
